Ver 0.6.9

diff --git a/pisafe-beta b/pisafe-beta
--- a/pisafe-beta
+++ b/pisafe-beta
@@ -10,7 +10,7 @@ COPYRIGHT="By Richard Reed 2018 - 2021"
 #echo empty the /root/.local/share/Trash folders to free up room
 
 SCRIPTNAME="${0##*/}"
-SCRIPTVER="0.6.8"
+SCRIPTVER="0.6.9"
 PRODUCTNAME="Pi Safe"
 PRODUCTCOMMENT="Backup-to or Restore-from an Image File"
 CURRENT_DIR=$(pwd)
@@ -120,13 +120,13 @@ calc_wt_size() {
 
 
 echo_or_msgbox(){
-    TITLE=$1
-    MSG=$2
+    local TITLE=$1
+    local MSG=$2
     
     if [ $INTERFACE = "CLI" ] ; then
         echo $TITLE $MSG
     else
-        whiptail --backtitle "$BACKTITLE" --title "$TITLE" --msgbox "$2" $WT_MB_HEIGHT $WT_MB_WIDTH
+        whiptail --backtitle "$BACKTITLE" --title "$TITLE" --msgbox "$MSG" $WT_MB_HEIGHT $WT_MB_WIDTH
     fi
 }    
 
@@ -147,14 +147,15 @@ echo_red_if_cli(){
 
 # this is probably unused, but good reference
 trim(){
-    STR=$1
+    local STR=$1
     echo $STR | sed 's/\s\s*/ /g' 
 }
 
 
 sd_size() {
     #get parameters
-    INDEV=$1
+    local INDEV=$1
+    
     lsblk /dev/$INDEV -d -n -o size  2> /dev/null
     if [ $? != 0 ]; then
         echo 0
@@ -164,7 +165,8 @@ sd_size() {
 
 sd_size_bytes() {
     #get parameters
-    INDEV=$1
+    local INDEV=$1
+    
     lsblk /dev/$INDEV -d -n -b -o size  2> /dev/null
     if [ $? != 0 ]; then
         echo 0
@@ -178,7 +180,8 @@ sd_card_name(){
 
 
 folder_size() {
-    FOLDER=$1
+    local FOLDER=$1
+    
     if [ -d $FOLDER ] ; then
         sudo du -sh $FOLDER | cut -d'/' -f1 | sed 's/\s\s*/ /g'
     else
@@ -188,7 +191,8 @@ folder_size() {
 
 
 file_size_kbytes() {
-    FILE=$1
+    local FILE=$1
+    
     if [ -f $FILE ] ; then
         ls -s $FILE | cut -d' ' -f1
     else
@@ -199,7 +203,7 @@ file_size_kbytes() {
 
 image_size() {
     #get parameters
-    INFILE=$1
+    local INFILE=$1
     
     case $(file_ext $INFILE) in
         img)
@@ -224,7 +228,7 @@ image_size() {
 
 image_size_bytes() {
     #get parameters
-    INFILE=$1
+    local INFILE=$1
     
     case $(file_ext $INFILE) in
         img)
@@ -265,7 +269,7 @@ freespace_bytes() {
 
 
 file_base() {
-    fullfilename=$1
+    local fullfilename=$1
     
     filename=$(basename "$fullfilename")
     fname="${filename%.*}"
@@ -274,7 +278,7 @@ file_base() {
 
 
 file_ext() {
-    fullfilename=$1
+    local fullfilename=$1
     
     filename=$(basename "$fullfilename")
     ext="${filename##*.}"
@@ -286,15 +290,18 @@ file_ext() {
 
 
 list_sd_devices() {
-    DEVICES=$(lsblk -d -n -o NAME,VENDOR,MODEL,SIZE /dev/sd? 2> /dev/null | grep -v $(boot_disk) )
+    local DEVICES=
+    DEVICES=$(lsblk -d -n -o NAME,VENDOR,MODEL,SIZE /dev/sd?  2> /dev/null | grep -v $(boot_disk) )   
     EXIT_CODE=$?
+    
+#echo diag: list_sd_devices. exit code= $EXIT_CODE.    
 
     if [ $EXIT_CODE != 0 ]; then
-        return 1
+        return $EXIT_CODE
     fi
     
     echo "${DEVICES[@]}"
-    return 0
+    #return 0
   }
   
 
@@ -310,8 +317,7 @@ boot_disk() {
     elif [[ $BOOT_PARTITION =~ "sd" ]]; then
         BOOT_DRIVE=${BOOT_PARTITION:0:3}
     else
-        return 1  # can't find boot disk
-
+        return 2  # can't find boot disk
     fi    
     echo $BOOT_DRIVE
 }
@@ -321,7 +327,7 @@ list_image_files(){
     ls -1 -s -h -w1 *.img *.zip *.xz *.gz 2> /dev/null | sed 's/ /     /' 
     EXIT_CODE=$?
     if [ $EXIT_CODE != 0 ] ; then
-        return 1
+        return $EXIT_CODE
     fi
 }
 
@@ -581,7 +587,7 @@ check_for_supported_file_extention(){
 }
 
 
-read_sd(){
+do_backup_get_input(){
     #get parameters
     INDEV=$1  #use global vars
 #echo INDE1=$INDEV    
@@ -597,7 +603,6 @@ read_sd(){
     
     
     case $COMPRESSION in
-    
         -1 | -2 | -3 | -4 | -5 | -6 | -7 | -8 | -9 )
             #echo Compression=$COMPRESSION of 9
         ;;
@@ -610,23 +615,24 @@ read_sd(){
     esac
     
 
-  
+
     #GET INDEV
     if [ $INTERFACE = "CLI" ] ; then
-#echo read_sd-$INDEV
         cli_get_sddevice  $INDEV  # this sets global variable INDEV and OUTDEV
         #gui_get_sddevice  # this sets global variable INDEV and OUTDEV
         EXIT_CODE=$?
-        echo SD-card name= \'$(lsblk -d -n -l -o NAME,VENDOR,MODEL,SIZE /dev/$INDEV 2> /dev/null)\'
-        echo SD-card size= $(sd_size $INDEV)
+        #echo SD-card name= \'$(lsblk -d -n -l -o NAME,VENDOR,MODEL,SIZE /dev/$INDEV 2> /dev/null)\'
+        #echo SD-card size= $(sd_size $INDEV)
         #echo SD-card TrashSize = $(folder_size /home/pi/.local/share/Trash)
     else  # GUI
-        #GOOD CODE
-        INDEV=$(gui_get_sddevice)
+        #INDEV=$(gui_get_sddevice)
+        gui_get_sddevice
         EXIT_CODE=$?
     fi
+    
+    
     if [ $EXIT_CODE != 0 ]; then
-        echo_or_msgbox "ERROR"  "no SD cards found"
+        #echo_or_msgbox "ERROR $EXIT_CODE: "  "no SD cards found"
         return $EXIT_CODE
     fi    
     
@@ -673,6 +679,7 @@ read_sd(){
     if [ $INTERFACE = "CLI" ] ; then
         echo
         read -p "Create image-file "\'$OUTFILE\'" from "\'/dev/$INDEV\'" [y,N] ?"  -n 1 -r RESULT
+        echo
     else
         whiptail  --backtitle "$BACKTITLE" --title "READ : Create Image-file" --defaultno --yesno "Create image-file '$OUTFILE' from '/dev/$INDEV'  \n\nA good 8GB card on a Pi4 takes about 9 minutes."   $WT_HEIGHT $WT_WIDTH
         EXIT_CODE=$?
@@ -690,7 +697,7 @@ read_sd(){
         fi
     
     
-        # this actually does the work!!
+        # this next line actually does the work!!
         do_backup $INDEV $OUTFILE
       
       
@@ -717,14 +724,14 @@ read_sd(){
 do_backup(){
     # This reads  /dev/$INDEV to $OUTFILE and compresses it 
     # Expecting 2 parameters    INDEV and OUTFILE
-    INDEV=$1
-    OUTFILE=$2
+    local INDEV=$1
+    local OUTFILE=$2
     
     #echo 1 - sudo dd bs=4M if=/dev/$INDEV of=$OUTFILE.img status=progress conv=fsync 
     #echo 2 - sudo pishrink.sh $OUTFILE.img
     #echo 3 - zip -db -dd -m $OUTFILE.zip $OUTFILE.img
     
-    echo_white BACKUP...
+    echo_white $PRODUCTNAME BACKUP...
     echo "IN-DEV='$INDEV'"
     echo "OUT-FILE='$OUTFILE'"
     echo
@@ -771,8 +778,8 @@ do_backup(){
         ;;
         
         zip)
-            FILESIZE_M=$(( $(file_size_kbytes $OUTFILE_BASE.img) / 1024))
-            DOTSIZE=$(( $FILESIZE_M / 50 ))
+            local FILESIZE_M=$(( $(file_size_kbytes $OUTFILE_BASE.img) / 1024))
+            local DOTSIZE=$(( $FILESIZE_M / 50 ))
             echo Dot size=$DOTSIZE MB
             echo -n "                      $(file_base $OUTFILE).img"
             echo ".........20........40........60........80........100%"
@@ -800,15 +807,17 @@ do_backup(){
     TIME4=$(date +%s)
     echo_white  Step 3 took $(elapsed_time $TIME3 $TIME4)
     
-    echo_white Backup done. Total time $(elapsed_time $TIME1 $TIME4). Press any key to continue...
-    read -n1
+    if [ $INTERFACE = "GUI" ]; then
+        echo
+        echo_white Backup done. Total time $(elapsed_time $TIME1 $TIME4). Press any key to continue...
+        read -n1
+    fi
 }
-
 
 
 cli_get_sddevice(){
 #echo _cli-get-$INDEV
-SDDEV=$1
+local SDDEV=$1
 #echo cli_get_sddevic-$SDDEV
     echo
     echo_white Getting SD-card ...
@@ -821,7 +830,7 @@ SDDEV=$1
         list_sd_devices
         EXIT_CODE=$?
         if [ $EXIT_CODE != 0 ]; then
-            echo ERROR: No SD-cards found.
+            echo_red ERROR:  No SD-cards found.
             return $EXIT_CODE
         fi
         echo
@@ -932,8 +941,6 @@ get_outfile(){
 
 
 gui_get_sddevice(){
-    #INDEV=$1
-
     FIELD_SEPERATOR="|"
 
     #get this list of sd divices and add a field seperator |    
@@ -941,8 +948,10 @@ gui_get_sddevice(){
     #options=($(lsblk -d -n -o NAME,VENDOR,MODEL,SIZE /dev/sd? | sed 's/ ./ | /'))
     options=($(list_sd_devices | sed 's/ ./ '$FIELD_SEPERATOR' /'))
     unset IFS
-
-    if [ -z  "$options" ]; then
+   # if [ -z  "$options" ]; then
+    if [ -z  "${options[@]}" ]; then
+#echo ERROR 6  gui_get_sddevice
+        echo_or_msgbox "ERROR" "No SD cards found." 
         return 1
     fi
 
@@ -951,7 +960,44 @@ gui_get_sddevice(){
     unset IFS   
      
     echo $DEVICE_SELECTED
+    OUTDEV=$DEVICE_SELECTED
+    INDEV=$DEVICE_SELECTED
+    return 0
 }
+
+
+gui_get_sddevice_X(){
+#echo _cli-get-$INDEV
+#local SDDEV=$1
+#echo cli_get_sddevic-$SDDEV
+    FIELD_SEPERATOR="|"
+    IFS=$'\n'
+    #echo
+    #echo_white Getting SD-card ...
+   # while [ -z "$SDDEV" ] || [ ! -e "/dev/$SDDEV" ] ; do
+        #if ! [ -z "$SDDEV" ] ; then
+        #    echo_red /dev/$SDDEV not found.
+        #fi    
+ #       echo_white Available SD-card devices are:
+ #       echo
+        list_sd_devices
+        EXIT_CODE=$?
+        if [ $EXIT_CODE != 0 ]; then
+            echo ERROR in cli_get_sddevice:  No SD-cards found.
+            return $EXIT_CODE
+        fi
+        echo
+        echo "Enter SD-card device name (eg: sda)"
+        read SDDEV
+    #done
+        # currently sets both INDEV and OUTDEV
+        OUTDEV=$SDDEV
+        INDEV=$SDDEV
+        echo $SDDEV
+        echo SD-card name=\'$(sd_card_name $SDDEV)\'
+        echo SD-card size=$(sd_size $SDDEV)
+}
+
 
 
 
@@ -983,16 +1029,18 @@ check_for_img_file(){
     
     
     if [ ! -z $(file_ext $IMG) ] && [ $(file_ext $IMG) == "img" ]; then
- 
         echo_if_cli $IMG [OK]
-        
+        return 0
        # fi
     else
-        if [ $INTERFACE = "CLI" ] ; then
-            echo_red WARNING ... No image file found in $INFILE
-        else
-            whiptail  --backtitle "$BACKTITLE" --title WARNING --msgbox "No image found in $INFILE" $WT_MB_WIDTH $WT_MB_HEIGHT
-        fi
+        echo_or_msgbox ERROR "No image found in '$INFILE'"
+        return 1
+        
+        #if [ $INTERFACE = "CLI" ] ; then
+        #    echo_red WARNING ... No image file found in $INFILE
+        #else
+        #    whiptail  --backtitle "$BACKTITLE" --title WARNING --msgbox "No image found in $INFILE" $WT_MB_HEIGHT $WT_MB_WIDTH 
+        #fi
     fi    
 }
 
@@ -1038,14 +1086,15 @@ check_out_device_size (){
             read -p "You must type 'OK' to continue:"  -r RESULT
             if ! [ $RESULT == "OK" ]; then
                 echo Exiting...
-                exit
+                return 1
+                #exit
             fi
         else
             whiptail  --backtitle "$BACKTITLE" --title WARNING --defaultno --yesno "'$(sd_card_name  $OUTDEV)' is larger than 16GB.  \n\nAre you sure it is the right device?"    $WT_MB_HEIGHT  $WT_MB_WIDTH
             #whiptail --title WARNING --yesno "SD-card is larger than 16GB.  Are you sure it is the right device?"    $WT_HEIGHT  $WT_WIDTH
             EXIT_CODE=$?
             if [ $EXIT_CODE != 0 ];  then
-                exit $EXIT_CODE
+                return $EXIT_CODE
             fi
         fi
     else
@@ -1075,7 +1124,7 @@ check_if_imagefile_will_fit_on_device(){
 }
 
 
-write_sd() {
+do_restore_get_input() {
     #get parameters
     INFILE=$1
     OUTDEV=$2
@@ -1099,23 +1148,23 @@ write_sd() {
     check_for_img_file $INFILE
     EXIT_CODE=$?
     if [ $EXIT_CODE != 0 ]; then
-        whiptail --backtitle "$BACKTITLE" --title ERROR --msgbox "Not enought free space on drive " $WT_MB_HEIGHT $WT_MB_WIDTH
         return $EXIT_CODE
     fi 
 
 
+#echo break 1
     # get out device
     if [ $INTERFACE = "CLI" ] ; then
-        cli_get_sddevice   # this sets global variable OUTDEV
+        cli_get_sddevice $OUTDEV  # this sets global variable OUTDEV
         EXIT_CODE=$?
     else
-        OUTDEV=$(gui_get_sddevice)
+        gui_get_sddevice        # this sets global variable OUTDEV
         EXIT_CODE=$?
     fi
-    
     if [ $EXIT_CODE != 0 ]; then
         return $EXIT_CODE
     fi    
+       
 
     check_out_device_size $OUTDEV  
     EXIT_CODE=$?
@@ -1187,10 +1236,10 @@ You can remove '$(sd_card_name $OUTDEV)' now. \
 do_restore(){
     # Expecting 2 parameters    INFILE and OUTDEV
     # This writes $INFILE to /dev/$OUTDEV
-    INFILE=$1
-    OUTDEV=$2
+    local INFILE=$1
+    local OUTDEV=$2
     
-    echo_white RESTORE...
+    echo_white $PRODUCTNAME RESTORE...
     echo "IN-FILE='$INFILE'"
     echo "OUT-DEV='$OUTDEV'"
     echo
@@ -1211,7 +1260,7 @@ do_restore(){
     date
     TIME1=$(date +%s)
 
-    INFILEEXT=$(file_ext $INFILE)
+    local INFILEEXT=$(file_ext $INFILE)
     
     echo        
     echo_white "Writing $(image_size $INFILE) to SD-card $OUTFILE ... "    
@@ -1243,10 +1292,12 @@ do_restore(){
 
     esac        
     TIME2=$(date +%s)
-    echo
     
-    echo_white "Restore done. Total time $(elapsed_time $TIME1 $TIME2). Press any key to continue..."
-    read -n1
+    if [ $INTERFACE = "GUI" ]; then
+        echo
+        echo_white "Restore done. Total time $(elapsed_time $TIME1 $TIME2). Press any key to continue..."
+        read -n1
+    fi
 }
 
 
@@ -1387,6 +1438,7 @@ StartupNotify=false" > "$PRODUCTNAME.desktop"
 
 
 gui_menu(){
+    INTERFACE="GUI"
     while true
     do
         MENU_CHOICE=$(whiptail \
@@ -1408,12 +1460,11 @@ gui_menu(){
         #echo $MENU_CHOICE
         case $MENU_CHOICE in
             BACKUP)
-                INTERFACE="GUI"
-                read_sd
+                do_backup_get_input
             ;;
             
             RESTORE)
-                write_sd
+                do_restore_get_input
             ;;
             
             LIST)
@@ -1463,27 +1514,23 @@ get_tools
 FILE_SELECTED=""
 DEVICE_SELECTED=""
 
-
+INTERFACE="CLI"
 
 case $1 in
     
     list)
-        INTERFACE="CLI"
         list_info
     ;;
     
     read|backup)
-        INTERFACE="CLI"
-        read_sd $2 $3 $4
+        do_backup_get_input $2 $3 $4
     ;;
     
     write|restore)
-        INTERFACE="CLI"
-        write_sd $2 $3
+        do_restore_get_input $2 $3
     ;;
     
     install)
-        INTERFACE="CLI"
         install
     ;;
     
@@ -1492,12 +1539,10 @@ case $1 in
     ;;
     
     menu)
-        INTERFACE="GUI"
         gui_menu
     ;;
     
     help|-h|--help)
-        INTERFACE="CLI"
         cli_help
     ;;
     
